"""init schema

Revision ID: 7fd982d46e27
Revises: 
Create Date: 2026-03-16 21:57:26.275842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd982d46e27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'files', 'organizations', ['org_id'], ['id'])
    op.drop_constraint(op.f('users_supabase_user_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_supabase_user_id'), 'users', ['supabase_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_supabase_user_id'), table_name='users')
    op.create_unique_constraint(op.f('users_supabase_user_id_key'), 'users', ['supabase_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'files', type_='foreignkey')
    # ### end Alembic commands ###
