"""Unified Lex Schema

Revision ID: ad18522944c1
Revises: 516ad88eed71
Create Date: 2026-05-01 14:32:50.706992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad18522944c1'
down_revision: Union[str, Sequence[str], None] = '516ad88eed71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('intelligence_status', sa.Enum('PENDING', 'PARTIAL', 'READY', name='intelligencestatus'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_org_id'), 'workspaces', ['org_id'], unique=False)
    op.create_table('deadline_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('obligation_description', sa.Text(), nullable=False),
    sa.Column('obligation_type', sa.Enum('RESPONSE', 'FILING', 'NOTICE', 'PAYMENT', 'OTHER', name='obligationtype'), nullable=False),
    sa.Column('raw_date_expression', sa.Text(), nullable=False),
    sa.Column('resolved_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_status', sa.Enum('RESOLVED', 'RELATIVE_UNRESOLVED', 'CONFLICTED', name='deadlineresolutionstatus'), nullable=False),
    sa.Column('conflict_flag', sa.Boolean(), nullable=False),
    sa.Column('source_clause_a', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_clause_b', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'OVERDUE', 'COMPLETED', 'SUPERSEDED', name='deadlinestatus'), nullable=False),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadline_registry_workspace_id'), 'deadline_registry', ['workspace_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('file_type', sa.Enum('DIGITAL_PDF', 'SCANNED_PDF', 'DOCX', name='documenttype'), nullable=True),
    sa.Column('r2_key', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', 'DUPLICATE', name='documentstatus'), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('intelligence_stages_complete', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_documents_org_id'), 'documents', ['org_id'], unique=False)
    op.create_index(op.f('ix_documents_upload_date'), 'documents', ['upload_date'], unique=False)
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_table('workspace_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_sessions_user_id'), 'workspace_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_sessions_workspace_id'), 'workspace_sessions', ['workspace_id'], unique=False)
    op.create_table('defined_terms_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('term', sa.String(length=500), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('clause_reference', sa.String(length=200), nullable=False),
    sa.Column('conflict_flag', sa.Boolean(), nullable=False),
    sa.Column('conflict_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defined_terms_registry_workspace_id'), 'defined_terms_registry', ['workspace_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_text', sa.Text(), nullable=False),
    sa.Column('goal_hash', sa.String(length=64), nullable=True),
    sa.Column('document_subset', postgresql.ARRAY(sa.Uuid()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workspace_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_session_id'), 'goals', ['session_id'], unique=False)
    op.create_index(op.f('ix_goals_workspace_id'), 'goals', ['workspace_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('intent', sa.Enum('ANALYZE', 'REASON', 'ACT', 'UNKNOWN', name='intenttype'), nullable=False),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('intent_reasoning', sa.Text(), nullable=True),
    sa.Column('intent_confirmed_by_human', sa.Boolean(), nullable=False),
    sa.Column('confirmed_intent', sa.Enum('ANALYZE', 'REASON', 'ACT', 'UNKNOWN', name='confirmed_intent_type'), nullable=True),
    sa.Column('status', sa.Enum('CLASSIFYING', 'AWAITING_INTENT_CONFIRMATION', 'RETRIEVING', 'EXPANDING', 'REASONING', 'DRAFTING', 'AWAITING_APPROVAL', 'EXECUTING', 'REVISING', 'RECOVERING', 'COMPLETED', 'ESCALATED', 'CANCELLED', 'FAILED', name='workflowstatus'), nullable=False),
    sa.Column('langgraph_checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_ref', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_goal_id'), 'workflow_executions', ['goal_id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.Enum('DRAFT_RESPONSE', 'FILE_DOCUMENT', 'SEND_NOTICE', 'UPDATE_CASE_TRACKER', 'SET_REMINDER', 'ESCALATE_TO_COUNSEL', name='actiontype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DETECTED', 'CONFIRMED', 'DRAFTING', 'AWAITING_APPROVAL', 'APPROVED', 'EXECUTING', 'EXECUTED', 'FAILED', 'ESCALATED', 'CANCELLED', name='actionstatus'), nullable=False),
    sa.Column('source_clause_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deadline_id', sa.Uuid(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('task_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deadline_id'], ['deadline_registry.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_workflow_id'), 'actions', ['workflow_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supporting_citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reference_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('definitional_conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('escalation_type', sa.Enum('INSUFFICIENT_COVERAGE', 'DEFINITIONAL_CONFLICT', 'STRUCTURAL_AMBIGUITY', name='escalationtype'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_workflow_id'), 'findings', ['workflow_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'USED', name='approvalstatus'), nullable=False),
    sa.Column('actor', sa.Uuid(), nullable=True),
    sa.Column('decision_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('draft_r2_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['actor'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_action_id'), 'approval_requests', ['action_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_token_hash'), 'approval_requests', ['token_hash'], unique=True)
    op.create_index(op.f('ix_approval_requests_workflow_id'), 'approval_requests', ['workflow_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('llm_prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('full_input_r2_key', sa.String(length=500), nullable=True),
    sa.Column('full_output_r2_key', sa.String(length=500), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('external_reference_id', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_workflow_id'), 'audit_log', ['workflow_id'], unique=False)
    op.create_table('tool_call_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'COMPENSATED', 'COMPENSATION_FAILED', name='toolcallstatus'), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('response_summary', sa.Text(), nullable=True),
    sa.Column('external_reference', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_call_log_idempotency_key'), 'tool_call_log', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_tool_call_log_workflow_id'), 'tool_call_log', ['workflow_id'], unique=False)

    # === START DATA MIGRATION ===
    # 1. Create a Default Workspace for any orgs that have files
    op.execute("""
        INSERT INTO workspaces (id, org_id, name, document_count, intelligence_status, created_at, last_active_at)
        SELECT gen_random_uuid(), org_id, 'Default Workspace', count(id), 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
        FROM files
        GROUP BY org_id
    """)
    # 2. Migrate files to documents
    op.execute("""
        INSERT INTO documents (id, workspace_id, org_id, filename, file_hash, r2_key, status, upload_date, content)
        SELECT 
            gen_random_uuid(), 
            (SELECT id FROM workspaces WHERE workspaces.org_id = files.org_id AND workspaces.name = 'Default Workspace' LIMIT 1),
            org_id, 
            filename, 
            file_hash, 
            'legacy/' || filename, 
            CASE 
                WHEN status::text = 'READY' THEN 'READY'::documentstatus
                WHEN status::text = 'PROCESSING' THEN 'PROCESSING'::documentstatus
                WHEN status::text = 'FAILED' THEN 'FAILED'::documentstatus
                ELSE 'PENDING'::documentstatus
            END,
            upload_date,
            content
        FROM files
    """)
    # === END DATA MIGRATION ===

    op.drop_index(op.f('ix_files_file_hash'), table_name='files')
    op.drop_index(op.f('ix_files_org_id'), table_name='files')
    op.drop_index(op.f('ix_files_status'), table_name='files')
    op.drop_index(op.f('ix_files_upload_date'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'READY', 'FAILED', name='filestatus'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('files_org_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('files_pkey'))
    )
    op.create_index(op.f('ix_files_upload_date'), 'files', ['upload_date'], unique=False)
    op.create_index(op.f('ix_files_status'), 'files', ['status'], unique=False)
    op.create_index(op.f('ix_files_org_id'), 'files', ['org_id'], unique=False)
    op.create_index(op.f('ix_files_file_hash'), 'files', ['file_hash'], unique=False)
    op.drop_index(op.f('ix_tool_call_log_workflow_id'), table_name='tool_call_log')
    op.drop_index(op.f('ix_tool_call_log_idempotency_key'), table_name='tool_call_log')
    op.drop_table('tool_call_log')
    op.drop_index(op.f('ix_audit_log_workflow_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_approval_requests_workflow_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_token_hash'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_action_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_findings_workflow_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_actions_workflow_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_workflow_executions_goal_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_goals_workspace_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_session_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_defined_terms_registry_workspace_id'), table_name='defined_terms_registry')
    op.drop_table('defined_terms_registry')
    op.drop_index(op.f('ix_workspace_sessions_workspace_id'), table_name='workspace_sessions')
    op.drop_index(op.f('ix_workspace_sessions_user_id'), table_name='workspace_sessions')
    op.drop_table('workspace_sessions')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_upload_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_org_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_deadline_registry_workspace_id'), table_name='deadline_registry')
    op.drop_table('deadline_registry')
    op.drop_index(op.f('ix_workspaces_org_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
